version: '3'
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: ./dockers/docker-file
        image: andika2000/dev-laravel
        container_name: app-asianet
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        user: www-data
        #user: root
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www
            - ./dockers/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver-asianet
        restart: unless-stopped
        tty: true
        ports:
            - "8210:80"
        volumes:
            - ./:/var/www
            - ./dockers/nginx/conf.d/:/etc/nginx/conf.d/

    #MySQL Service
    db_asianet:
        image: mysql:5.7.22
        container_name: db-asianet
        restart: unless-stopped
        tty: true
        ports:
            - "3210:3306"
        environment:
            MYSQL_DATABASE: asianet
            MYSQL_ROOT_PASSWORD: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./dockers/mysql/data:/var/lib/mysql/
            - ./dockers/mysql/my.cnf:/etc/mysql/my.cnf
